### ISSUE TITLE
reactfire 사용 제안합니다.

### ISSUE THREAD

**Issue by Kyun2da** [Kyun2da/sejongCabinet#160]
- [깃허브 주소](https://github.com/FirebaseExtended/reactfire)

파이어베이스 구조를 계속 고민하다가 파이어베이스 오픈소스인 reactfire를 발견하였습니다. 

- Easy realtime updates for your function components
- Access Firebase libraries from any component 
- Built-in Support for prefetching
- Safely configure Firebase libraries

4가지의 장점이 존재한다고 합니다. 공식문서 확인해보시고 사용의견 부탁드립니다 :)

**Comment by Kyun2da** [comment]
@Jongminfire 아니면 auth랑 database쪽을 참고하며 직접 구현해도 좋을 듯 합니다!

**Comment by Jongminfire** [comment]
공식문서를 좀 더 공부 해봐야겠지만 사용하면 좋을 것 같습니다 ~~

**Comment by Kyun2da** [comment]
@Jongminfire 아 방금 확인해봤는데 저희가 참고하고있는 react-firebase-hooks로 충분할 것 같습니다.  이슈 닫겠습니다.
