### ISSUE TITLE
캐비넷 추가하면서 알게된 데이터 이슈일 수도(?) 있는 일

### ISSUE THREAD

**Issue by Kyun2da** [Kyun2da/sejongCabinet#174]
![image](https://user-images.githubusercontent.com/50328132/120167132-5716c800-c238-11eb-9a9b-d528397be2ea.png)
현재 캐비넷은 위의 그림과 같이 번호 0부터 시작이 되는 형식입니다.
![image](https://user-images.githubusercontent.com/50328132/120167285-83cadf80-c238-11eb-953f-271da8c4cfff.png)
캐비넷 추가나 삭제를 반복하다 보면 위의 그림과 같이 중간 번호가 없어지는 현상이 발생하는데요
![image](https://user-images.githubusercontent.com/50328132/120167355-9a713680-c238-11eb-9611-2a7cd5f0be5e.png)
이 것을 리덕스로 자바스크립트에서 받아오면 위의 그림과 같이 중간에 null 값이 생기게 됩니다.
이를 메인페이지에서 캐비넷을 렌더링할때 null값은 제외하셔야 될 것 같아서 이슈 띄워 놓습니다!

**Comment by Jongminfire** [comment]
파이어베이스 사물함 데이터로 연결하면서 null값 제외하도록 하겠습니다~
