### ISSUE TITLE
사물함 최대 가로길이에 대한 의견 부탁드립니다

### ISSUE THREAD

**Issue by Jongminfire** [Kyun2da/sejongCabinet#177]
## 현재 개발상황

현재 PC와 모바일 둘 다 최대 가로길이 12에 맞춰놓고 사물함 버튼의 크기를 구성했습니다.

사물함의 가로길이와 세로길이에 맞춰서 화면에 딱 맞게 버튼의 크기를 구성하는 방법도 있는데, 이렇게 되면 사물함을 움직일 때 마다 버튼의 크기가 계속 바뀔 수 있어서 버튼의 크기는 고정하는 것이 좋을 것 같습니다.

## 문제점

<div>

<img src="https://user-images.githubusercontent.com/51112542/120210671-02407500-c26b-11eb-93cd-c6691561f6d2.png" width="45%" height="500px">

<img src="https://user-images.githubusercontent.com/51112542/120210694-0a001980-c26b-11eb-8923-07b15a18877f.png" width="45%" height="500px">

</div>

왼쪽이 v1 오른쪽이 v2 입니다.

최대 길이를 12로 고정해서 사물함 버튼이 많이 작아졌는데 이부분을 어떻게 할지 의견 부탁드려요~

**Comment by Kyun2da** [comment]
네 버튼 크기는 고정하는게 좋을 것 같습니다~
