### ISSUE TITLE
유저 데이터 초기화 부분 제안합니다

### ISSUE THREAD

**Issue by Jongminfire** [Kyun2da/sejongCabinet#184]
## 문제점

![image](https://user-images.githubusercontent.com/51112542/120611739-72c7db80-c48f-11eb-817a-713e8cc21ab4.png)

현재 유저 데이터 초기화는 `cabinetIdx` 에 0이 들어가게 되는데 firebase cabinet 데이터가 0부터 시작하기 때문에 이후 사물함 관련 처리 할 때 문제가 있습니다 (이미 신청 했을 때 다른 사물함을 신청하려는 경우 등)

## 제안하는 해결방안

![image](https://user-images.githubusercontent.com/51112542/120611983-ae62a580-c48f-11eb-8a26-7e1467f9e04b.png)

위 처럼 유저 데이터 초기화를 진행 할 때 인덱스 값을 null로 두는 방안 제안합니다

**Comment by Kyun2da** [comment]
@Jongminfire 좋은 것 같습니다. 그리고 저쪽 바꾸실 때 Signup.tsx쪽 부분도 같이 바꾸면 좋을 것 같습니다.
![image](https://user-images.githubusercontent.com/50328132/120614374-203bee80-c492-11eb-8975-f1a969f1e87d.png)

**Comment by Kyun2da** [comment]
@Jongminfire  아 추가로 cabinetTitle을 number로 하여 CabinetTab의 번호를 지정하는게 어떨까요?

그래야 관리자 페이지에서 캐비넷 제목을 바꿀때 예약된 사람의 캐비넷 타이틀까지 바꿔주지 않아도 될 것 같습니다.

**Comment by Jongminfire** [comment]
> @Jongminfire 아 추가로 cabinetTitle을 number로 하여 CabinetTab의 번호를 지정하는게 어떨까요?
> 
> 그래야 관리자 페이지에서 캐비넷 제목을 바꿀때 예약된 사람의 캐비넷 타이틀까지 바꿔주지 않아도 될 것 같습니다.

좋은 의견인 것 같습니다~
