### ISSUE TITLE
사진 없을 때 보여줄 대체 사진 만들어주실수 있을까요?

### ISSUE THREAD

**Issue by Kyun2da** [Kyun2da/sejongCabinet#195]
![image](https://user-images.githubusercontent.com/50328132/120894459-68563f00-c653-11eb-8d6a-8f1825e39f51.png)

관리자가 사진을 등록하지 않았을 때 보여줄 대체 사진이 있었으면 좋겠는데 혹시 간단하게 제작 가능하실까요? 저거랑 비슷한 폰트가 뭔지 몰라서 요청드립니다..! 사진 없음 이런식으로 간단하게만 만들어주시면 감사하겠습니다.

**Comment by Jongminfire** [comment]
대체 사진 만들어보도록 하겠습니다~
