### ISSUE TITLE
예전에 썼었던 react-responsive 사용 제안 합니다.

### ISSUE THREAD

**Issue by Kyun2da** [Kyun2da/sejongCabinet#196]
현재 반응형을 쓰기위해 isMobile 함수를 쓰고 있는 것을 보았습니다. 이 함수는 화면의 크기가 작아졌다를 실시간으로 인지 못해서 이를 해결해주는 react-responsive를 쓰는 것을 제안합니다.

**Comment by Jongminfire** [comment]
네 좋은 의견인것 같습니다~
