### ISSUE TITLE
모바일 서버 상태 표시 관련

### ISSUE THREAD

**Issue by Jongminfire** [Kyun2da/sejongCabinet#198]
![image](https://user-images.githubusercontent.com/51112542/120915454-a64c7500-c6de-11eb-95d0-9fd50511e49e.png)

모바일 화면에서 서버 상태 아이콘을 헤더에 넣으면 복잡하게 보일 것 같습니다.
지금 서버가 닫히면 위처럼 선택된 사물함을 표시하는 대신  사물함 신청이 불가능하다는 메세지가 나오는데 이것으로 대체하면 어떨까요?

**Comment by Kyun2da** [comment]
좋은 것 같습니다! 이슈 닫도록 하겠습니다
