### ISSUE TITLE
관리자 페이지 사물함 사진 스타일 관련

### ISSUE THREAD

**Issue by Jongminfire** [Kyun2da/sejongCabinet#203]
고생하셨습니다 👍

관리자 페이지 사진 부분에서 height이 고정되어 있어서 이미지가 잘리는 문제가 있을 수 있을 것 같은데, 이미지의 maxHeight을 설정하고 그 크기에 맞게 사진을 조정해서 사진 전체를 볼 수 있는 방법은 어떨까요?

그리고 사진의 종류를 나타내는 텍스트가 좀 더 직관적으로 보이면 좋을 것 같습니다

두 부분 변경해서 가안으로 만들어봤는데 어떤 것 같은지 피드백 해주시면 감사하겠습니다

![image](https://user-images.githubusercontent.com/51112542/121317379-34299980-c945-11eb-8b7a-859f4fe13bd1.png)

_Originally posted by @Jongminfire in https://github.com/Kyun2da/sejongCabinet/issues/202#issuecomment-857485939_

**Comment by Kyun2da** [comment]
@Jongminfire  이미지 height를 고정한 이유가 초기에 이미지 사진 height가 세팅이 안되어서 사진을 보여주려고 해놓았던 것인데 되는지 확인해보고 구현해보도록 하겠습니다 :)

**Comment by Kyun2da** [comment]
#205 로 해결하여 이슈 닫습니다.
