### ISSUE TITLE
메인페이지에서 사물함 사진을 띄우기 위한 인덱스 문제 질문

### ISSUE THREAD

**Issue by Kyun2da** [Kyun2da/sejongCabinet#204]
현재 메인 페이지의 index를 끌어당겨와서 사진 swiper의 사진들을 구별하여 보여주려고 하는데,
파이어베이스의 1,3,4,5 번이었던 인덱스가 메인페이지에서는 0,1,2,3 으로 렌더링이 이루어져있는 것 같습니다.

혹시 이 부분 1,3,4,5로 인덱스를 변경이 가능한가요?

**Comment by Jongminfire** [comment]
Cabinet 탭을 구현하는 SwipeableViews의 index가 컨텐츠에 따라 순차적으로 하나씩 쌓이는 방식이라 그런 것 같습니다..

CabinetContents 컴포넌트의 index 인자가 1,3,4,5 값인데 이 값으로 구현이 가능할까요?

아니면 메인 페이지에서 cabinet의 파이어베이스 인덱스를 저장하는 배열을 넘겨주고 swiper의 index와 같이 사용해야 할 것 같습니다

**Comment by Kyun2da** [comment]
인덱스로 해결하여서 이슈 닫습니다. 감사합니다 :)
